apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: rhaiis-demo
type: kubernetes.io/podmanconfigjson
data:
  config.json: <your podman config secret. https://access.redhat.com/articles/RegistryAuthentication>
