apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhaiis-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhaiis-runner
  template:
    metadata:
      labels:
        app: rhaiis-runner
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
        - name: rhaiis
          image: registry.redhat.io/rhaiis/vllm-cuda-rhel9:3.0.0
          args: ["--model", "RedHatAI/Llama-3.2-1B-Instruct-FP8"]
          ports:
            - containerPort: 8000
          #          resources:
          #            limits:
          #              nvidia.com/gpu: 1
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HUGGING_FACE_TOKEN
            - name: HF_HUB_OFFLINE
              value: "0"
            - name: VLLM_NO_USAGE_STATS
              value: "1"
            - name: VLLM_LOGGING_LEVEL
              value: "DEBUG"
          volumeMounts:
            - name: cache-volume
              mountPath: /opt/app-root/src/.cache
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: rhaiis-runner-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
#      securityContext:
#        runAsNonRoot: true
#        allowPrivilegeEscalation: false
#        seccompProfile:
#          type: RuntimeDefault
